import './normalize.test';
import './google-auth.test';
import './google-error.test';
import './sheet-schema.test';
import './sheets.test';
import './metrics.test';
import './email-activity.test';
import './tracking.test';
import './auth.test';
import './lead-filter.test';
import './lead-update.test';
import './lead-disposition.test';
import './county-leads.test';
import './http-json.test';
console.log('all local unit tests passed');
