'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import type { DashboardData, RedactedLead } from '@/lib/types';
import AppNav from './app-nav';
import LeadDrawer from './lead-drawer';

export default function IncompleteLeadsClient(){
  const [data,setData]=useState<DashboardData|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [openLead,setOpenLead]=useState<string|null>(null);const [query,setQuery]=useState('');const [source,setSource]=useState<'all'|'expired'|'withdrawn'|'active'>('all');const [updating,setUpdating]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch('/api/dashboard',{cache:'no-store'});if(response.status===401){window.location.href='/login';return;}const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to load incomplete leads.');setData(payload as DashboardData);}catch(err){setError(err instanceof Error?err.message:'Unable to load incomplete leads.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const leads=useMemo(()=>{const q=query.trim().toLowerCase();return (data?.leads||[]).filter(lead=>lead.missingDetails&&!lead.badLead).filter(lead=>source==='all'||lead.sourceKey===source).filter(lead=>!q||`${lead.firstName} ${lead.address} ${lead.city} ${lead.state}`.toLowerCase().includes(q));},[data,query,source]);
  async function markBad(lead:RedactedLead){if(!window.confirm('Mark this as a Bad Lead? It will be removed from active and incomplete queues and excluded from outreach, but the source row will be retained.'))return;setUpdating(lead.id);setError('');try{const response=await fetch(`/api/leads/${encodeURIComponent(lead.id)}/disposition`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({disposition:'Bad Lead'})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to mark bad lead.');await load();}catch(err){setError(err instanceof Error?err.message:'Unable to mark bad lead.');}finally{setUpdating(null);}}
  async function logout(){await fetch('/api/auth/logout',{method:'POST'});window.location.href='/login';}
  return <main className="dashboard-shell"><div className="dashboard-wrap"><AppNav current="incomplete"/><header className="topbar"><div><div className="eyebrow">SEETO REALTY · OWNER PROSPECTING</div><h1>Incomplete leads</h1><p>Complete missing owner, contact, and property details before outreach.</p></div><div className="topbar-actions"><button className="secondary-button" disabled={loading} onClick={()=>void load()}>{loading?'Refreshing…':'Refresh'}</button><button className="ghost-button" onClick={logout}>Log out</button></div></header>
    {error?<section className="setup-alert"><strong>Unable to complete request</strong><span>{error}</span><button className="secondary-button" onClick={()=>void load()}>Try again</button></section>:null}
    <section className="panel leads-panel"><div className="panel-header"><div><div className="section-kicker">ENRICHMENT QUEUE</div><h2>{leads.length.toLocaleString()} incomplete lead{leads.length===1?'':'s'}</h2></div></div>
      <div className="incomplete-filters"><input aria-label="Search incomplete leads" placeholder="Search name, property, city…" value={query} onChange={e=>setQuery(e.target.value)}/><select value={source} onChange={e=>setSource(e.target.value as typeof source)}><option value="all">All sources</option><option value="expired">Expired</option><option value="withdrawn">Withdrawn</option><option value="active">Active</option></select></div>
      <div className="table-wrap desktop-leads"><table><thead><tr><th>Lead</th><th>Property</th><th>Source</th><th>Missing</th><th>Actions</th></tr></thead><tbody>{leads.slice(0,500).map(lead=><tr key={lead.id}><td><strong>{lead.firstName}</strong></td><td><strong>{lead.address||'No address'}</strong><small>{[lead.city,lead.state].filter(Boolean).join(', ')}</small></td><td><span className={`source-chip source-${lead.sourceKey}`}>{lead.sourceKey}</span></td><td><div className="missing-chips">{lead.missingFields.map(field=><span className="needs-details" key={field}>{field}</span>)}</div></td><td><div className="row-actions"><button className="text-button" onClick={()=>setOpenLead(lead.id)}>Edit details</button><button className="danger-link" disabled={updating===lead.id} onClick={()=>void markBad(lead)}>{updating===lead.id?'Updating…':'Mark Bad Lead'}</button></div></td></tr>)}</tbody></table></div>
      <div className="mobile-leads">{leads.slice(0,500).map(lead=><div className="mobile-lead-card" key={lead.id}><div><strong>{lead.firstName}</strong><span>{lead.address||'No address'}</span></div><div className="missing-chips">{lead.missingFields.map(field=><span className="needs-details" key={field}>{field}</span>)}</div><div className="row-actions"><button className="text-button" onClick={()=>setOpenLead(lead.id)}>Edit details</button><button className="danger-link" disabled={updating===lead.id} onClick={()=>void markBad(lead)}>Mark Bad Lead</button></div></div>)}</div>
      {leads.length>500?<p className="panel-note">Showing the first 500 matching leads. Narrow the search to find a specific record.</p>:null}
    </section>
  </div><LeadDrawer id={openLead} onClose={()=>setOpenLead(null)} onSaved={()=>void load()}/></main>;
}
